/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import views.shared.components.dlgAddTicketType;
import controllers.EventController;
import controllers.TicketController;
import controllers.UserController;
import java.awt.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.*;
import models.Event;
import models.TicketType;
import models.User;
import raven.datetime.component.date.DatePicker;
import raven.datetime.component.time.TimePicker;
import utility.Session;
import views.*;
import views.shared.components.pnlEvent;

/**
 *
 * @author andre
 */
public class EventView extends BaseView {

    /**
     * Creates new form DashboardView
     */
    
    private EventController eventController;
    private TicketController ticketController = new TicketController(db);;

    private UserController userController =  new UserController(db);
    private List<TicketType> ticketTypes;
    
    //Ticket handling stuff
    
    public EventView(){
        initComponents();
    }
    
    public EventView(Event event) {
        initComponents();
        
        updateDetails(event);
    }

    private void updateDetails(Event daEvent){
        hdrMain.setText(daEvent.getName());
        lblLocation.setText("Event Location: " + daEvent.getLocation());
        lblStartDate.setText("Event Start Date: " + daEvent.getFormattedStartTime());
        lblEndDate.setText("Event End Date: " + daEvent.getFormattedEndTime());
        lblTicketPrice.setText("");
        lblQuantityLeft.setText("");
        txtDescription.setText(daEvent.getDescription());
        
        cmbTicketType.removeAllItems();
        
        ticketTypes = ticketController.getTicketTypesByEventId(daEvent.getId());

        for (TicketType ticket : ticketTypes) {
            cmbTicketType.addItem(ticket.getName()); // Add the name of each ticket type
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavBar1 = new views.shared.components.pnlNavBar();
        scrlMain = new javax.swing.JScrollPane();
        pnlMain = new javax.swing.JPanel();
        hdrBuyTickets = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblEventName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAddToCart = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblEndDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTicketPrice = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        hdrMain = new javax.swing.JLabel();
        cmbTicketType = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();
        lblEndDate3 = new javax.swing.JLabel();
        lblPricePerTicket = new javax.swing.JLabel();
        lblEndDate4 = new javax.swing.JLabel();
        lblQuantityLeft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eventure - Events");
        setResizable(false);

        pnlMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        hdrBuyTickets.setFont(new java.awt.Font("Riffic Free Medium", 0, 36)); // NOI18N
        hdrBuyTickets.setText("BUY TICKETS:");
        hdrBuyTickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hdrBuyTickets.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblStartDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStartDate.setText("Event Start Date:");
        lblStartDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));

        lblEventName1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEventName1.setText("Event Description:");
        lblEventName1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnAddToCart.setBackground(new java.awt.Color(153, 0, 153));
        btnAddToCart.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddToCartMouseClicked(evt);
            }
        });
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 0, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Events");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEndDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEndDate.setText("Event End Date:");
        lblEndDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTicketPrice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTicketPrice.setText("Actual Price");
        lblTicketPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 20));
        lblTicketPrice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblLocation.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblLocation.setText("Event Location:");
        lblLocation.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 20, 20));

        hdrMain.setFont(new java.awt.Font("Riffic Free Medium", 0, 64)); // NOI18N
        hdrMain.setText("EVENT NAME");
        hdrMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        hdrMain.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        cmbTicketType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbTicketType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTicketType.setPreferredSize(new java.awt.Dimension(300, 60));
        cmbTicketType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTicketTypeMouseClicked(evt);
            }
        });
        cmbTicketType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTicketTypeActionPerformed(evt);
            }
        });

        spnQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnQuantity.setPreferredSize(new java.awt.Dimension(120, 60));

        lblEndDate3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEndDate3.setText("Ticket Type:");
        lblEndDate3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 20));

        lblPricePerTicket.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPricePerTicket.setText("Price per Ticket:");
        lblPricePerTicket.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 20));

        lblEndDate4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEndDate4.setText("Quantity:");
        lblEndDate4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 20));

        lblQuantityLeft.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantityLeft.setText("Quantity Left");
        lblQuantityLeft.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddToCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlMainLayout.createSequentialGroup()
                                    .addComponent(lblEventName1)
                                    .addGap(284, 284, 284))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblStartDate)
                            .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hdrBuyTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblEndDate3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addComponent(lblPricePerTicket)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTicketPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(338, 338, 338)
                                .addComponent(lblQuantityLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(hdrMain, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(331, Short.MAX_VALUE)))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                    .addContainerGap(644, Short.MAX_VALUE)
                    .addComponent(lblEndDate4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(462, 462, 462)))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStartDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEventName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(hdrBuyTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTicketType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndDate3))
                        .addGap(30, 30, 30)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTicketPrice)
                            .addComponent(lblPricePerTicket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuantityLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jSeparator1)))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMainLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(hdrMain, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(461, Short.MAX_VALUE)))
            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                    .addContainerGap(362, Short.MAX_VALUE)
                    .addComponent(lblEndDate4)
                    .addGap(139, 139, 139)))
        );

        scrlMain.setViewportView(pnlMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(scrlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        this.dispose();
        EventsView eventsView = new EventsView();
        // Optionally pass the database connection or user info if needed
        //DashboardController dashboardController = new DashboardController(dashboardView, dbConnection);
        eventsView.setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void btnAddToCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToCartMouseClicked
        // TODO add your handling code here:
        // Gather input data

    }//GEN-LAST:event_btnAddToCartMouseClicked

    private void cmbTicketTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTicketTypeActionPerformed
        // TODO add your handling code here:
        String selectedTicketName = (String) cmbTicketType.getSelectedItem();

        // Find the selected TicketType object based on the name
        TicketType selectedTicketType = null;
        
        if (ticketTypes != null){
            for (TicketType ticket : ticketTypes) {
                if (ticket.getName().equals(selectedTicketName)) {
                    selectedTicketType = ticket;
                    break;
                }
            }
        }
       
        // If a valid ticket type is found, update the price label
        if (selectedTicketType != null) {
            BigDecimal price = selectedTicketType.getPrice();
            int quantityLeft = selectedTicketType.getQuantity();
            lblTicketPrice.setText("PHP " + String.format("%.2f", price)); // Update label with price in PHP
            lblQuantityLeft.setText(quantityLeft + " tickets left");
        }
    }//GEN-LAST:event_cmbTicketTypeActionPerformed

    private void cmbTicketTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTicketTypeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbTicketTypeMouseClicked

    public void myInitComponents() {  
        eventController = new EventController(db);
        ticketController = new TicketController(db);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
          
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbTicketType;
    private javax.swing.JLabel hdrBuyTickets;
    private javax.swing.JLabel hdrMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblEndDate3;
    private javax.swing.JLabel lblEndDate4;
    private javax.swing.JLabel lblEventName1;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPricePerTicket;
    private javax.swing.JLabel lblQuantityLeft;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTicketPrice;
    private javax.swing.JPanel pnlMain;
    private views.shared.components.pnlNavBar pnlNavBar1;
    private javax.swing.JScrollPane scrlMain;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
