/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.EventController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.*;
import models.Event;
import views.*;

/**
 *
 * @author andre
 */
public class EventsView extends BaseView {

    /**
     * Creates new form DashboardView
     */
    
    private EventController controller;
    
    public EventsView() {
        initComponents();
        myInitComponents();
        loadEventCards();  // Load events and display them as cards
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavBar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblNBDashboard = new javax.swing.JLabel();
        lblNBEvents = new javax.swing.JLabel();
        lblNBProfile = new javax.swing.JLabel();
        lblNBCheckout = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        hdrDashboard1 = new javax.swing.JLabel();
        btnCreateEvent = new javax.swing.JButton();
        pneEventCards = new javax.swing.JScrollPane();
        pnlEventCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eventure - Events");
        setResizable(false);

        pnlNavBar.setBackground(new java.awt.Color(155, 0, 155));
        pnlNavBar.setMinimumSize(new java.awt.Dimension(75, 23));
        pnlNavBar.setPreferredSize(new java.awt.Dimension(320, 720));
        pnlNavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setText("THE LOGO SHOULD BE HERE");
        lblLogo.setPreferredSize(new java.awt.Dimension(225, 55));
        pnlNavBar.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, -1, -1));

        lblNBDashboard.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblNBDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblNBDashboard.setText("Dashboard");
        lblNBDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNBDashboardMouseClicked(evt);
            }
        });
        pnlNavBar.add(lblNBDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 35, -1, -1));

        lblNBEvents.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblNBEvents.setForeground(new java.awt.Color(255, 255, 255));
        lblNBEvents.setText("Events");
        lblNBEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNBEventsMouseClicked(evt);
            }
        });
        pnlNavBar.add(lblNBEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 35, -1, -1));

        lblNBProfile.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblNBProfile.setForeground(new java.awt.Color(255, 255, 255));
        lblNBProfile.setText("Profile");
        lblNBProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNBProfileMouseClicked(evt);
            }
        });
        pnlNavBar.add(lblNBProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 35, -1, -1));

        lblNBCheckout.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblNBCheckout.setForeground(new java.awt.Color(255, 255, 255));
        lblNBCheckout.setText("Checkout");
        lblNBCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNBCheckoutMouseClicked(evt);
            }
        });
        pnlNavBar.add(lblNBCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 35, -1, -1));

        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hdrDashboard1.setFont(new java.awt.Font("Riffic Free Medium", 0, 64)); // NOI18N
        hdrDashboard1.setText("EVENTS");
        pnlMain.add(hdrDashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        btnCreateEvent.setBackground(new java.awt.Color(153, 0, 153));
        btnCreateEvent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCreateEvent.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateEvent.setText("Create Event");
        btnCreateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEventActionPerformed(evt);
            }
        });
        pnlMain.add(btnCreateEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, -1, -1));

        pnlEventCards.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 0, 0));
        pneEventCards.setViewportView(pnlEventCards);

        pnlMain.add(pneEventCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1200, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavBar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblNBEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNBEventsMouseClicked
        // TODO add your handling code here:
        // Open the Events page when Events label is clicked
        EventsView view = new EventsView(); // Create a new page for Events
        view.setVisible(true);
        this.dispose(); // Close the current window (Dashboard)
        
    }//GEN-LAST:event_lblNBEventsMouseClicked

    private void lblNBDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNBDashboardMouseClicked
        // TODO add your handling code here:
        DashboardView view = new DashboardView(); // Create a new page for Events
        view.setVisible(true);
        this.dispose(); // Close the current window (Dashboard)
    }//GEN-LAST:event_lblNBDashboardMouseClicked

    private void lblNBCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNBCheckoutMouseClicked
        // TODO add your handling code here:
        CheckoutView view = new CheckoutView(); // Create a new page for Events
        view.setVisible(true);
        this.dispose(); // Close the current window (Dashboard)
    }//GEN-LAST:event_lblNBCheckoutMouseClicked

    private void lblNBProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNBProfileMouseClicked
        // TODO add your handling code here:
        ProfileView view = new ProfileView(); // Create a new page for Events
        view.setVisible(true);
        this.dispose(); // Close the current window (Dashboard)
    }//GEN-LAST:event_lblNBProfileMouseClicked

    private void btnCreateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateEventActionPerformed

    public void loadEventCards() {
        List<Event> events = controller.getEvents(); // Fetch events from controller

        pnlEventCards.removeAll(); // Clear existing components

        for (Event event : events) {
            JPanel eventPanel = new JPanel();
            eventPanel.setLayout(new BoxLayout(eventPanel, BoxLayout.Y_AXIS));
            eventPanel.setBackground(new Color(128, 0, 128)); // Purple background
            eventPanel.setPreferredSize(new Dimension(250, 250));

            // Add labels
            JLabel lblName = new JLabel(event.getName());
            lblName.setFont(new Font("Tahoma", Font.BOLD, 24));
            lblName.setForeground(Color.WHITE);

            JLabel lblDescription = new JLabel(event.getDescription());
            lblDescription.setFont(new Font("Tahoma", Font.PLAIN, 12));
            lblDescription.setForeground(Color.WHITE);

            JLabel lblDate = new JLabel(event.getDate());
            lblDate.setFont(new Font("Tahoma", Font.BOLD, 12));
            lblDate.setForeground(Color.WHITE);

            // Add components to panel
            eventPanel.add(lblName);
            eventPanel.add(lblDescription);
            eventPanel.add(lblDate);

            // Add margin around event panel
            eventPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

            pnlEventCards.add(eventPanel);
            pnlEventCards.add(Box.createRigidArea(new Dimension(0, 20))); // Vertical gap
        }

        pnlEventCards.setPreferredSize(new Dimension(
            pneEventCards.getViewport().getWidth(),
            pnlEventCards.getPreferredSize().height + ((events.size() / 4) * 260) // Adjust height based on card count
        ));
        
        pnlEventCards.revalidate();
        pnlEventCards.repaint();
    }



    public void myInitComponents() {  
        controller = new EventController(db);
        
        lblLogo.setText("");
        lblLogo.setSize(new Dimension(225, 55)); // Set desired width and height
        lblLogo.revalidate();
        lblLogo.repaint();
        
        ImageIcon logoIcon = new ImageIcon(getClass().getResource("/storage/images/logo.png"));
        
        Image img = logoIcon.getImage();
        Image imgScale = img.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        
        lblLogo.setIcon(scaledIcon); // NOI18N
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
          
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEvent;
    private javax.swing.JLabel hdrDashboard1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNBCheckout;
    private javax.swing.JLabel lblNBDashboard;
    private javax.swing.JLabel lblNBEvents;
    private javax.swing.JLabel lblNBProfile;
    private javax.swing.JScrollPane pneEventCards;
    private javax.swing.JPanel pnlEventCards;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNavBar;
    // End of variables declaration//GEN-END:variables
}
