/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.shared.components;


import java.awt.Dimension;
import java.awt.Font;
import java.awt.Window;
import javax.swing.*;
import javax.swing.border.*;
import models.TicketType;
import views.EventView;
import models.Event;
import utility.Session;
import views.BaseView;
import views.OrganizerEventView;

/**
 *
 * @author andre
 */
public class pnlAdminStat extends javax.swing.JPanel {

    /**
     * Creates new form pnlEvent
     */
    private String statName;
    private String stat;
    
    
    public pnlAdminStat() {
        initComponents();
    }
    
    public pnlAdminStat(String statName, String stat) {   
        initComponents();
        
        this.statName = statName;
        this.stat = stat;
        
        this.lblStatName.setText(statName);
        this.lblStat.setText(stat);
        
        // Get the preferred size of the label
        int fontSize = 14; // default font size
        if (stat.length() > 10) {
            fontSize = 12;
        } else if (stat.length() > 20) {
            fontSize = 10;
        } else if (stat.length() > 30) {
            fontSize = 8;
        }

        lblStat.setFont(new Font(lblStat.getFont().getName(), lblStat.getFont().getStyle(), fontSize));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblStatName = new javax.swing.JLabel();
        lblStat = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 0, 128));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setRequestFocusEnabled(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        lblStatName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStatName.setForeground(new java.awt.Color(255, 255, 255));
        lblStatName.setText("Stat Name");
        lblStatName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(lblStatName, gridBagConstraints);

        lblStat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStat.setForeground(new java.awt.Color(255, 255, 255));
        lblStat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStat.setText("Stat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 50, 0);
        add(lblStat, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblStat;
    private javax.swing.JLabel lblStatName;
    // End of variables declaration//GEN-END:variables
}
