/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.shared.components;

import java.awt.event.*;

/**
 *
 * @author andre
 */
public class pnlAdminProfileSideBar extends javax.swing.JPanel {

    /**
     * Creates new form pnlProfileSideBar
     */
    public pnlAdminProfileSideBar() {
        initComponents();
    }
    public pnlAdminProfileSideBar(ActionListener actionListener) {
        initComponents();
        addMouseListeners(actionListener);
    }
    
    private void addMouseListeners(ActionListener actionListener) {
        lblOverview.addMouseListener(new LabelMouseListener("Overview", actionListener));
      
    }
    
    private class LabelMouseListener extends MouseAdapter {
        private String label;
        private ActionListener actionListener;

        public LabelMouseListener(String label, ActionListener actionListener) {
            this.label = label;
            this.actionListener = actionListener;
        }

        @Override
        public void mouseClicked(MouseEvent e) {
            //System.out.println("IM CLICKING ON " + label.toUpperCase() + "!!!");
            actionListener.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, label));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblOverview = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 0, 128));
        setPreferredSize(new java.awt.Dimension(320, 600));
        setLayout(new java.awt.GridBagLayout());

        lblOverview.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblOverview.setForeground(new java.awt.Color(255, 255, 255));
        lblOverview.setText("Overview");
        lblOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOverviewMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(lblOverview, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void lblOverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOverviewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOverviewMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblOverview;
    // End of variables declaration//GEN-END:variables
}
