/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.shared.components;


import java.awt.Window;
import javax.swing.*;
import javax.swing.border.*;
import models.TicketType;
import views.EventView;
import models.Event;
import utility.Session;
import views.BaseView;
import views.OrganizerEventView;

/**
 *
 * @author andre
 */
public class pnlEvent extends javax.swing.JPanel {

    /**
     * Creates new form pnlEvent
     */
    private String name;
    private String location;
    private String description;
    private String startTime;
    private String endTime;
    
    private Event daEvent;
    
    public pnlEvent() {
        initComponents();
    }
    
    public pnlEvent(Event daEvent) {
         this.daEvent = daEvent;
          
        initComponents();
        
        this.name = daEvent.getName();
        this.location = daEvent.getLocation();
        this.description = daEvent.getDescription();
        this.startTime = daEvent.getFormattedStartTime();
        this.endTime = daEvent.getFormattedEndTime();
        
        this.lblName.setText(name);
        this.lblDescription.setText(description);
        this.lblDate.setText("Start: " + startTime + " - End: " + endTime);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 0, 128));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setRequestFocusEnabled(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Event Name");
        add(lblName);

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Event Description");
        add(lblDescription);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Event Date");
        add(lblDate);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        BaseView parentWindow = (BaseView) SwingUtilities.getWindowAncestor(this);
        
        if (daEvent.getCreatorId() == Session.getCurrentUser().getId()){
            OrganizerEventView organizerEventView = new OrganizerEventView(daEvent, parentWindow);  // Assuming EventView is your class
            organizerEventView.setVisible(true);
        }
        else{
            EventView eventView = new EventView(daEvent);  // Assuming EventView is your class
            eventView.setVisible(true);
        }
        

        // Dispose of the current frame (this is the original window)
        parentWindow.dispose();  // This will close the current window
    }//GEN-LAST:event_formMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
