/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.shared.components;

import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;

/**
 *
 * @author andre
 */
public class pnlEvent extends javax.swing.JPanel {

    /**
     * Creates new form pnlEvent
     */
    private String name;
    private String description;
    private String date;
    
     private JPanel overlayPanel;
    
    public pnlEvent() {
        initComponents();
    }
    
    public pnlEvent(String name, String description, String date) {
        initComponents();
        
        this.name = name;
        this.description = description;
        this.date = date;
        
        this.lblName.setText(name);
        this.lblDescription.setText(description);
        this.lblDate.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 0, 128));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setRequestFocusEnabled(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lblName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Event Name");
        add(lblName);

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Event Description");
        add(lblDescription);

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Event Date");
        add(lblDate);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        showEventOverlay(name, description, date);
    }//GEN-LAST:event_formMouseClicked

    private void showEventOverlay(String name, String description, String date) {
        /// Access the parent panel of the current pnlEvent
        JPanel parentPanel = (JPanel) getParent();

        // Remove any existing overlay
        if (overlayPanel != null) {
            parentPanel.remove(overlayPanel);
        }

        // Create a new overlay panel (semi-transparent dark background)
        overlayPanel = new JPanel();
        overlayPanel.setBackground(new Color(0, 0, 0, 150)); // semi-transparent black
        overlayPanel.setLayout(new BorderLayout());
        overlayPanel.setBounds(0, 0, parentPanel.getWidth(), parentPanel.getHeight()); // Full size of the parent panel

        // Create the event details panel to appear on top
        JPanel detailsPanel = new JPanel();
        detailsPanel.setLayout(new BoxLayout(detailsPanel, BoxLayout.Y_AXIS));
        detailsPanel.setBackground(Color.WHITE);
        detailsPanel.setBorder(new EmptyBorder(20, 20, 20, 20));

        JLabel lblEventName = new JLabel("Event: " + name);
        lblEventName.setFont(new Font("Tahoma", Font.BOLD, 20));
        detailsPanel.add(lblEventName);

        JLabel lblEventDesc = new JLabel("Description: " + description);
        lblEventDesc.setFont(new Font("Tahoma", Font.PLAIN, 16));
        detailsPanel.add(lblEventDesc);

        JLabel lblEventDate = new JLabel("Date: " + date);
        lblEventDate.setFont(new Font("Tahoma", Font.PLAIN, 16));
        detailsPanel.add(lblEventDate);

        // Add the details panel to the overlay
        overlayPanel.add(detailsPanel, BorderLayout.CENTER);

        // Add the overlay to the parent panel
        parentPanel.add(overlayPanel, BorderLayout.CENTER);

        // Revalidate and repaint the parent panel to reflect the overlay
        parentPanel.revalidate();
        parentPanel.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
